### ISSUE TITLE
Add app page with link to App/Play stores

### ISSUE THREAD

**Issue by TylerCarberry** [RowanACM/ACM_Site#5]
Right now rowanacm.org/app gets forwarded to to the Play Store. Instead, make this an actual page with a description of the app and a button that brings you to the Play Store.

**Comment by csteward24** [comment]
#9 adds the page, but the description still needs to be added

**Comment by csteward24** [comment]
https://github.com/csteward24/ACM_Site/commit/b9de7e9760954ccccdc8b56d5b1d9d73fa022493 adds a link to the page in the navbar

**Comment by SirSaunders** [comment]
like it like it, but might change it to a firebase dynamic link so when you click it it will auto open Play store for android or app store for ios with our download page. 

I'll close this and open a new issue for it.
